# Generated by Django 4.2.6 on 2023-10-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='places_1_to_32',
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('places__gte', 1), ('places__lte', 32)), name='places_1_to_32'),
        ),
    ]
