# Generated by Django 4.2.6 on 2023-11-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_booking_room_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('room', 'check_in', 'check_out'), name='unique_booking'),
        ),
    ]
