# Generated by Django 4.2.6 on 2023-11-01 13:59

import core.rooms.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_booking_unique_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(core.rooms.models.TsTzRange('check_in', 'check_out', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('room', '=')], name='exclude_overlapping_reservations'),
        ),
    ]
